name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.ref_name }}'
  cancel-in-progress: true

jobs:
  ci:
    runs-on: windows-latest
    name: CI
    steps:

    - name: Download and extract F3D Windows
      shell: powershell
      run: |
        mkdir f3d
        cd f3d
        curl.exe -L --output f3d.zip --url https://github.com/f3d-app/f3d/releases/download/v2.4.0/F3D-2.4.0-Windows-x86_64.zip
        C:\'Program Files'\7-Zip\7z.exe x f3d.zip

    - name: Download and extract data and baselines
      shell: powershell
      run: |
        mkdir data
        cd data
        curl.exe -L --output cow.vtp --url https://github.com/f3d-app/f3d-superbuild/raw/main/testing/data/cow.vtp
        curl.exe -L --output TestSimple.png --url https://github.com/f3d-app/f3d-superbuild/raw/main/testing/baselines/TestSimple.png

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: 'source'
        fetch-depth: 0

    - name: Test action
      uses: ./source/
      with:
        path: f3d

    - name: Check F3D can render with success
      shell: bash
      run: ./f3d/F3D-2.4.0-Windows-x86_64/bin/f3d.exe ./data/cow.vtp --resolution=300,300 --ref=./data/TestSimple.png
